/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedHandoffsNewRouteImport } from './routes/_authenticated/handoffs.new'
import { Route as AuthenticatedHandoffsIdRouteImport } from './routes/_authenticated/handoffs.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedHandoffsIdIndexRouteImport } from './routes/_authenticated/handoffs.$id.index'
import { Route as AuthenticatedHandoffsIdUpdatesRouteImport } from './routes/_authenticated/handoffs.$id.updates'
import { Route as AuthenticatedHandoffsIdSourcesRouteImport } from './routes/_authenticated/handoffs.$id.sources'
import { Route as AuthenticatedHandoffsIdNoteRouteImport } from './routes/_authenticated/handoffs.$id.note'
import { Route as AuthenticatedHandoffsIdChatRouteImport } from './routes/_authenticated/handoffs.$id.chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedHandoffsNewRoute =
  AuthenticatedHandoffsNewRouteImport.update({
    id: '/handoffs/new',
    path: '/handoffs/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHandoffsIdRoute = AuthenticatedHandoffsIdRouteImport.update({
  id: '/handoffs/$id',
  path: '/handoffs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedHandoffsIdIndexRoute =
  AuthenticatedHandoffsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHandoffsIdRoute,
  } as any)
const AuthenticatedHandoffsIdUpdatesRoute =
  AuthenticatedHandoffsIdUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedHandoffsIdRoute,
  } as any)
const AuthenticatedHandoffsIdSourcesRoute =
  AuthenticatedHandoffsIdSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedHandoffsIdRoute,
  } as any)
const AuthenticatedHandoffsIdNoteRoute =
  AuthenticatedHandoffsIdNoteRouteImport.update({
    id: '/note',
    path: '/note',
    getParentRoute: () => AuthenticatedHandoffsIdRoute,
  } as any)
const AuthenticatedHandoffsIdChatRoute =
  AuthenticatedHandoffsIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedHandoffsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/handoffs/$id': typeof AuthenticatedHandoffsIdRouteWithChildren
  '/handoffs/new': typeof AuthenticatedHandoffsNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/handoffs/$id/chat': typeof AuthenticatedHandoffsIdChatRoute
  '/handoffs/$id/note': typeof AuthenticatedHandoffsIdNoteRoute
  '/handoffs/$id/sources': typeof AuthenticatedHandoffsIdSourcesRoute
  '/handoffs/$id/updates': typeof AuthenticatedHandoffsIdUpdatesRoute
  '/handoffs/$id/': typeof AuthenticatedHandoffsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/handoffs/new': typeof AuthenticatedHandoffsNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/handoffs/$id/chat': typeof AuthenticatedHandoffsIdChatRoute
  '/handoffs/$id/note': typeof AuthenticatedHandoffsIdNoteRoute
  '/handoffs/$id/sources': typeof AuthenticatedHandoffsIdSourcesRoute
  '/handoffs/$id/updates': typeof AuthenticatedHandoffsIdUpdatesRoute
  '/handoffs/$id': typeof AuthenticatedHandoffsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/handoffs/$id': typeof AuthenticatedHandoffsIdRouteWithChildren
  '/_authenticated/handoffs/new': typeof AuthenticatedHandoffsNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/handoffs/$id/chat': typeof AuthenticatedHandoffsIdChatRoute
  '/_authenticated/handoffs/$id/note': typeof AuthenticatedHandoffsIdNoteRoute
  '/_authenticated/handoffs/$id/sources': typeof AuthenticatedHandoffsIdSourcesRoute
  '/_authenticated/handoffs/$id/updates': typeof AuthenticatedHandoffsIdUpdatesRoute
  '/_authenticated/handoffs/$id/': typeof AuthenticatedHandoffsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/inbox'
    | '/admin/users'
    | '/handoffs/$id'
    | '/handoffs/new'
    | '/admin/'
    | '/handoffs/$id/chat'
    | '/handoffs/$id/note'
    | '/handoffs/$id/sources'
    | '/handoffs/$id/updates'
    | '/handoffs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/inbox'
    | '/admin/users'
    | '/handoffs/new'
    | '/admin'
    | '/handoffs/$id/chat'
    | '/handoffs/$id/note'
    | '/handoffs/$id/sources'
    | '/handoffs/$id/updates'
    | '/handoffs/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/admin/users'
    | '/_authenticated/handoffs/$id'
    | '/_authenticated/handoffs/new'
    | '/_authenticated/admin/'
    | '/_authenticated/handoffs/$id/chat'
    | '/_authenticated/handoffs/$id/note'
    | '/_authenticated/handoffs/$id/sources'
    | '/_authenticated/handoffs/$id/updates'
    | '/_authenticated/handoffs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/handoffs/new': {
      id: '/_authenticated/handoffs/new'
      path: '/handoffs/new'
      fullPath: '/handoffs/new'
      preLoaderRoute: typeof AuthenticatedHandoffsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/handoffs/$id': {
      id: '/_authenticated/handoffs/$id'
      path: '/handoffs/$id'
      fullPath: '/handoffs/$id'
      preLoaderRoute: typeof AuthenticatedHandoffsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/handoffs/$id/': {
      id: '/_authenticated/handoffs/$id/'
      path: '/'
      fullPath: '/handoffs/$id/'
      preLoaderRoute: typeof AuthenticatedHandoffsIdIndexRouteImport
      parentRoute: typeof AuthenticatedHandoffsIdRoute
    }
    '/_authenticated/handoffs/$id/updates': {
      id: '/_authenticated/handoffs/$id/updates'
      path: '/updates'
      fullPath: '/handoffs/$id/updates'
      preLoaderRoute: typeof AuthenticatedHandoffsIdUpdatesRouteImport
      parentRoute: typeof AuthenticatedHandoffsIdRoute
    }
    '/_authenticated/handoffs/$id/sources': {
      id: '/_authenticated/handoffs/$id/sources'
      path: '/sources'
      fullPath: '/handoffs/$id/sources'
      preLoaderRoute: typeof AuthenticatedHandoffsIdSourcesRouteImport
      parentRoute: typeof AuthenticatedHandoffsIdRoute
    }
    '/_authenticated/handoffs/$id/note': {
      id: '/_authenticated/handoffs/$id/note'
      path: '/note'
      fullPath: '/handoffs/$id/note'
      preLoaderRoute: typeof AuthenticatedHandoffsIdNoteRouteImport
      parentRoute: typeof AuthenticatedHandoffsIdRoute
    }
    '/_authenticated/handoffs/$id/chat': {
      id: '/_authenticated/handoffs/$id/chat'
      path: '/chat'
      fullPath: '/handoffs/$id/chat'
      preLoaderRoute: typeof AuthenticatedHandoffsIdChatRouteImport
      parentRoute: typeof AuthenticatedHandoffsIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedHandoffsIdRouteChildren {
  AuthenticatedHandoffsIdChatRoute: typeof AuthenticatedHandoffsIdChatRoute
  AuthenticatedHandoffsIdNoteRoute: typeof AuthenticatedHandoffsIdNoteRoute
  AuthenticatedHandoffsIdSourcesRoute: typeof AuthenticatedHandoffsIdSourcesRoute
  AuthenticatedHandoffsIdUpdatesRoute: typeof AuthenticatedHandoffsIdUpdatesRoute
  AuthenticatedHandoffsIdIndexRoute: typeof AuthenticatedHandoffsIdIndexRoute
}

const AuthenticatedHandoffsIdRouteChildren: AuthenticatedHandoffsIdRouteChildren =
  {
    AuthenticatedHandoffsIdChatRoute: AuthenticatedHandoffsIdChatRoute,
    AuthenticatedHandoffsIdNoteRoute: AuthenticatedHandoffsIdNoteRoute,
    AuthenticatedHandoffsIdSourcesRoute: AuthenticatedHandoffsIdSourcesRoute,
    AuthenticatedHandoffsIdUpdatesRoute: AuthenticatedHandoffsIdUpdatesRoute,
    AuthenticatedHandoffsIdIndexRoute: AuthenticatedHandoffsIdIndexRoute,
  }

const AuthenticatedHandoffsIdRouteWithChildren =
  AuthenticatedHandoffsIdRoute._addFileChildren(
    AuthenticatedHandoffsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedHandoffsIdRoute: typeof AuthenticatedHandoffsIdRouteWithChildren
  AuthenticatedHandoffsNewRoute: typeof AuthenticatedHandoffsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedHandoffsIdRoute: AuthenticatedHandoffsIdRouteWithChildren,
  AuthenticatedHandoffsNewRoute: AuthenticatedHandoffsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
